import React, { useState, useEffect } from 'react';

export default function AnalysisDashboard({ data }) {
  if (!data) return null;

  const { summary, risk_level, risk_rationale, flagged_clauses = [] } = data;
  const [openClauses, setOpenClauses] = useState({});
  const [meterWidth, setMeterWidth] = useState(0);

  const normalizedRisk = (risk_level || 'medium').toLowerCase();
  const riskClass = normalizedRisk === 'high' 
    ? 'risk-high' 
    : normalizedRisk === 'low' 
    ? 'risk-low' 
    : 'risk-medium';

  const riskScorePercentage = normalizedRisk === 'high' ? 85 : normalizedRisk === 'low' ? 25 : 55;

  useEffect(() => {
    const timer = setTimeout(() => {
      setMeterWidth(riskScorePercentage);
    }, 150);
    return () => clearTimeout(timer);
  }, [riskScorePercentage]);

  const toggleClause = (idx) => {
    setOpenClauses((prev) => ({ ...prev, [idx]: !prev[idx] }));
  };

  const getClauseTagClass = (type) => {
    const lower = (type || '').toLowerCase();
    if (lower.includes('renew') || lower.includes('sub')) return 'clause-tag-renewal';
    if (lower.includes('fee') || lower.includes('cost') || lower.includes('penalty')) return 'clause-tag-fee';
    if (lower.includes('data') || lower.includes('privacy') || lower.includes('share')) return 'clause-tag-data';
    return 'clause-tag-obligation';
  };

  // Export PDF Report
  const handleExportPDF = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    const clauseRows = flagged_clauses.map((c, i) => `
      <div style="margin-bottom: 15px; padding: 12px; border: 1px solid #ddd; border-radius: 6px;">
        <strong style="color: #d97706; text-transform: uppercase; font-size: 11px;">#${i + 1} ${c.type}</strong>
        <p style="margin: 6px 0; font-weight: bold; font-size: 13px;">What It Means For You:</p>
        <p style="margin: 0 0 8px 0; color: #333; font-size: 13px;">${c.explanation}</p>
        <blockquote style="margin: 0; padding-left: 10px; border-left: 3px solid #6366F1; color: #555; font-style: italic; font-size: 12px;">"${c.excerpt}"</blockquote>
      </div>
    `).join('');

    printWindow.document.write(`
      <html>
        <head>
          <title>Clario - Compliance Audit Report</title>
          <style>
            body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; padding: 30px; color: #111; line-height: 1.5; }
            h1 { color: #1e1b4b; font-size: 22px; border-bottom: 2px solid #6366F1; padding-bottom: 8px; }
            .badge { display: inline-block; padding: 4px 12px; border-radius: 12px; font-weight: bold; font-size: 12px; text-transform: uppercase; background: #fee2e2; color: #dc2626; }
            .summary { background: #f8fafc; padding: 15px; border-radius: 8px; margin: 20px 0; border: 1px solid #e2e8f0; }
          </style>
        </head>
        <body>
          <h1>Contract Guardian Compliance Audit Report</h1>
          <p><strong>Overall Risk Assessment:</strong> <span class="badge">${risk_level} Risk</span></p>
          <p><em>${risk_rationale}</em></p>
          
          <div class="summary">
            <h3 style="margin-top:0;">Executive Summary</h3>
            <p style="margin:0; font-size: 14px;">${summary}</p>
          </div>

          <h3>Flagged Legal Terms & Covenants (${flagged_clauses.length})</h3>
          ${clauseRows || '<p>No high-risk terms flagged.</p>'}

          <hr style="margin-top: 30px; border: none; border-top: 1px solid #eee;" />
          <p style="font-size: 10px; color: #777;">Generated by Clario. Informational purposes only.</p>
        </body>
      </html>
    `);

    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
      printWindow.print();
    }, 250);
  };

  return (
    <div className="dashboard">
      
      {/* ── Risk Assessment Banner ────────────────────────────── */}
      <div className={`risk-banner ${riskClass}`}>
        <div className="risk-banner-top flex justify-between items-start">
          <div className="flex items-center gap-3">
            <div className="risk-icon-wrap">
              <svg className="w-7 h-7" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
              </svg>
            </div>
            <div>
              <span className="risk-badge-label">Automated Compliance Assessment</span>
              <h2 className="risk-level-text">{risk_level || 'Moderate'} Risk Profile</h2>
            </div>
          </div>

          <button
            onClick={handleExportPDF}
            className="flex items-center gap-1.5 text-xs font-semibold bg-[#1F2D52] hover:bg-[#2A3A66] text-[#EEF2FF] px-3 py-1.5 rounded-lg border border-[#334078] transition-colors"
          >
            <svg className="w-4 h-4 text-[#6366F1]" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
            Export PDF
          </button>
        </div>

        {risk_rationale && (
          <p className="risk-rationale">{risk_rationale}</p>
        )}

        {/* Dynamic Risk Gauge */}
        <div className="risk-meter">
          <div className="meter-track">
            <div 
              className={`meter-fill meter-fill-${normalizedRisk}`} 
              style={{ width: `${meterWidth}%` }}
            />
            <div 
              className={`meter-thumb meter-thumb-${normalizedRisk}`} 
              style={{ left: `calc(${meterWidth}% - 7px)` }}
            />
          </div>
          <div className="meter-labels">
            <span>Low Exposure</span>
            <span>Moderate Concern</span>
            <span>High Risk Threshold</span>
          </div>
        </div>
      </div>

      {/* ── Executive Legal Summary ───────────────────────── */}
      <div className="summary-card">
        <div className="card-heading">
          <svg className="w-4 h-4 card-heading-icon" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
          </svg>
          <h3>Executive Legal Summary</h3>
        </div>
        <p className="summary-text">{summary || 'No audit summary generated.'}</p>
      </div>

      {/* ── Actionable Flagged Terms ─────────────────────────── */}
      <div className="clauses-section">
        <div className="card-heading">
          <svg className="w-4 h-4 card-heading-icon warn-color" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
          </svg>
          <h3>
            Flagged Legal Terms 
            <span className="clause-count-badge">{flagged_clauses.length}</span>
          </h3>
        </div>

        {flagged_clauses.length > 0 ? (
          <div className="clauses-list">
            {flagged_clauses.map((clause, idx) => {
              const isOpen = openClauses[idx] ?? true;
              return (
                <div key={idx} className={`clause-card ${isOpen ? 'clause-card-open' : ''}`}>
                  <button 
                    type="button" 
                    className="clause-card-header" 
                    onClick={() => toggleClause(idx)}
                  >
                    <div className="clause-header-left">
                      <span className={`clause-type-tag ${getClauseTagClass(clause.type)}`}>
                        {clause.type || 'Flagged Condition'}
                      </span>
                    </div>
                    <svg 
                      className={`w-4 h-4 clause-toggle-icon transition-transform ${isOpen ? 'rotate-180' : ''}`} 
                      fill="none" 
                      viewBox="0 0 24 24" 
                      stroke="currentColor"
                    >
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                    </svg>
                  </button>

                  {isOpen && (
                    <div className="clause-card-body">
                      {/* Plain-English Callout */}
                      <div className="clause-explanation">
                        <svg className="w-4 h-4 clause-warn-icon" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                        </svg>
                        <div>
                          <strong style={{ display: 'block', fontSize: '11px', textTransform: 'uppercase', color: 'var(--risk-mid)', marginBottom: '2px' }}>
                            What It Means For You
                          </strong>
                          <p>{clause.explanation}</p>
                        </div>
                      </div>

                      {/* Verbatim Legal Excerpt */}
                      <div className="clause-excerpt">
                        <span className="excerpt-label">Verbatim Contract Excerpt</span>
                        "{clause.excerpt}"
                      </div>
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        ) : (
          <div className="clauses-empty">
            <svg className="w-8 h-8 empty-shield" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
            </svg>
            <p>No high-risk terms or restrictive covenants were detected in this document.</p>
          </div>
        )}
      </div>

      <div className="dashboard-disclaimer">
        <span>* Automated legal audit provided for informational guidance and does not constitute formal legal counsel.</span>
      </div>

    </div>
  );
}